import React from 'react';

const Terms = () => (
  <div className="card">
    <h1>Terms of Use</h1>
    <p>CricForge is provided as an educational/demonstration cricket ecosystem platform. Match footage used in any
      replay-assisted scoring workflow must be licensed, user-provided, or otherwise permitted content - CricForge
      does not host or redistribute copyrighted broadcast footage.</p>
    <p>Simulated match outcomes are generated by a probability-driven engine and do not represent real-world results.
      Statistics and analytics are derived only from data entered or simulated within the platform.</p>
    <p className="muted">This is a project/demo document, not a legally binding agreement.</p>
  </div>
);

export default Terms;
